GET http://localhost:8000/api/language
    Authorization: bearer change-this-secret

###

GET http://localhost:8000/api/language/head
    Authorization: bearer change-this-secret

###

POST http://localhost:8000/api/user
Content-Type: application/json

{
    "username": "user",
    "password": "Password1!",
    "name": "name"
}

###

POST http://localhost:8000/api/user
Content-Type: application/json

{
    "username": "user",
    "password": "Password1!",
    "name": "name"
}

